services:
  backend:
    # image: $BACKEND_IMAGE
    # for local testing
    build:
      context: ./Backend
    ports:
      - 8000:8000
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: "diary"
      MYSQL_USER: "dbuser"
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "50m"

  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - .env
    volumes:
      - mysqldb:/var/lib/mysql
    restart: unless-stopped

  volumes:
    mysqldb:
