services:
  backend:
    # image: $BACKEND_IMAGE
    # for local testing
    build:
      context: ./Backend
    # ports:
    #   - 8000:8000
    depends_on: 
      - mysql
    restart: unless-stopped
    env_file:
      - .env.backend
      - .env.mysql.shared
      - path: .env.mysql.shared.secret
        required: false
      - path: .env.backend.secret
        required: false
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "50m"
    networks:
      - app_network
    volumes:
      - ./Backend:/app

  mysql:
    image: mysql
    environment:
      - TZ=Asia/Seoul
    env_file:
      - .env.mysql.shared
      - .env.mysql
      - path: .env.mysql.shared.secret
        required: false
      - path: .env.mysql.secret
        required: false
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - app_network

  flask:
    build:
      context: ./AI-Emotion-Detection
    volumes:
      - ./AI-Emotion-Detection/src:/app
      - ./AI-Emotion-Detection/model:/app/model
    # ports:
    #   - "5000:5000"
    networks:
      - app_network
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "50m"

  frontend:
    build:
      context: ./Frontend
    # ports:
    #   - 3000:3000
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "50m"
    networks:
      - app_network

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
    networks:
      - app_network
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "50m"

volumes:
  mysql-data:
    driver: local

networks:
  app_network:
    driver: bridge