services:
  backend:
    # image: $BACKEND_IMAGE
    # for local testing
    build:
      context: ./Backend
    ports:
      - 8000:8000
    depends_on: 
      - mysql
    restart: unless-stopped
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "50m"

  mysql:
    image: mysql
    env_file:
      - .env
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql-data:
    driver: local
