services:
  backend:
    # image: $BACKEND_IMAGE
    # for local testing
    build:
      context: ./Backend
    ports:
      - 8000:8000
    depends_on: 
      - mysql
    restart: unless-stopped
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "50m"
    networks:
      - app_network
    volumes:
      - ./Backend:/app

  mysql:
    image: mysql
    env_file:
      - .env
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - app_network

  flask:
    build:
      context: ./AI-Emotion-Detection
    volumes:
      - ./AI-Emotion-Detection/src:/app
      - ./AI-Emotion-Detection/model:/app/model
    ports:
      - "5000:5000"
    networks:
      - app_network

volumes:
  mysql-data:
    driver: local

networks:
  app_network:
    driver: bridge